CREATE USER IF NOT EXISTS 'User'@'localhost' IDENTIFIED BY 'fv_7qJ6j2_VY_T5';
GRANT ALL PRIVILEGES ON * . * TO 'User'@'localhost';

DROP DATABASE IF EXISTS BddSiteDeRencontre;
CREATE DATABASE IF NOT EXISTS BddSiteDeRencontre;

USE BddSiteDeRencontre;


CREATE TABLE IF NOT EXISTS Account ( 
	IdAccount INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Pseudo VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Sexe VARCHAR(30),
	FirstName VARCHAR(127),
	Name VARCHAR(127),
	Mail VARCHAR(255) NOT NULL,
	DateOfCreation DATETIME NOT NULL DEFAULT current_timestamp(),
	DateOfBirth DATE NOT NULL,
	Country VARCHAR(127) NOT NULL,
	City VARCHAR(127) NOT NULL,
	Street VARCHAR(127),
	AdressNumber INT,
	LoveSituation VARCHAR(30),
	Species VARCHAR(35),
	HumanoidGauge FLOAT(10),
	Size DECIMAL(9,2),
	Weight DECIMAL(9,2),
	EyeColor VARCHAR(30),
	Smoker INT(1),
	WelcomeMessage TEXT);


CREATE TABLE IF NOT EXISTS Admin (
	IdAccount INT NOT NULL PRIMARY KEY,
	FOREIGN KEY (IdAccount) REFERENCES Account(IdAccount) ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS Message ( 
	IdMessage INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IdSender INT NOT NULL,
	IdRecipient INT NOT NULL,
	DateSend DATETIME NOT NULL,
	Content TEXT,
	FOREIGN KEY (IdSender) REFERENCES Account(IdAccount) ON DELETE CASCADE,
	FOREIGN KEY (IdRecipient) REFERENCES Account(IdAccount) ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS Interest ( 
	IdInterest INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Interest VARCHAR(255) NOT NULL);


CREATE TABLE IF NOT EXISTS InterestLink ( 
	IdAccount INT NOT NULL,
	IdInterest INT NOT NULL,
	CONSTRAINT cle_pri PRIMARY KEY (IdAccount, IdInterest),
	FOREIGN KEY (IdAccount) REFERENCES Account(IdAccount) ON DELETE CASCADE,
	FOREIGN KEY (IdInterest) REFERENCES Interest(IdInterest) ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS Subscription (
	IdAccount INT NOT NULL,
	Start DATETIME NOT NULL DEFAULT current_timestamp(),
	End DATETIME NOT NULL,
	CONSTRAINT cle_pri PRIMARY KEY (IdAccount, Start),
	FOREIGN KEY (IdAccount) REFERENCES Account(IdAccount) ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS BlackList ( 
	IdAccount INT NOT NULL,
	IdBlocked INT NOT NULL,
	CONSTRAINT cle_pri PRIMARY KEY (IdAccount, IdBlocked),
	FOREIGN KEY (IdAccount) REFERENCES Account(IdAccount) ON DELETE CASCADE,
	FOREIGN KEY (IdBlocked) REFERENCES Account(IdAccount) ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS Image ( 
	IdAccount INT NOT NULL,
	IdImg INT NOT NULL,
	ImgFile VARCHAR(255) NOT NULL,
	CONSTRAINT cle_pri PRIMARY KEY (IdAccount, IdImg),
	FOREIGN KEY (IdAccount) REFERENCES Account(IdAccount) ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS Report ( 
	IdMessage INT NOT NULL PRIMARY KEY,
	Why TEXT,
	FOREIGN KEY (IdMessage) REFERENCES Message(IdMessage) ON DELETE CASCADE);